import { Product } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All Products', icon: 'Grid' },
  { id: 'kitchen', name: 'Kitchen & Dining', icon: 'Utensils' },
  { id: 'home', name: 'Home & Living', icon: 'Home' },
  { id: 'beauty', name: 'Beauty & Wellness', icon: 'Sparkles' },
  { id: 'electronics', name: 'Electronics & Gear', icon: 'Cpu' }
];

export const PRODUCTS: Product[] = [
  {
    id: 'levoit-air-purifier',
    name: 'Levoit Core True HEPA Air Purifier Tower',
    price: 125.00,
    originalPrice: 129.99,
    rating: 4.8,
    reviewsCount: 1642,
    category: 'home',
    image: '/images/levoit_air_purifier.png',
    description: 'VortexAir 3.0 technology true HEPA air filter purifier for allergen, odor, smoke and dust removal.',
    longDescription: 'Breathe pure, fresh air every day with the Levoit Core HEPA Air Purifier. Featuring advanced VortexAir 3.0 technology and a 3-stage filtration system, it effectively captures 99.97% of airborne particles as small as 0.3 microns. Clean pollen, pet dander, mold spores, wildfire smoke, and household odors in minutes. Perfect for bedrooms, offices, and living rooms, it operates at a whisper-quiet 24dB sound level to let you sleep undisturbed.',
    features: [
      '3-Stage True HEPA Filtration system',
      'Ultra-Silent QuietKEAP Sleep Mode (24dB)',
      'High-Efficiency VortexAir 360° Air Inflow',
      'ARC Formula Activated Carbon Filter for odors',
      'Sleek modern tower UI touch control panel'
    ],
    stock: 24,
    badge: 'Best Seller',
    isPopular: true
  },
  {
    id: 'satin-sheets-set',
    name: 'Luxury Silky Satin Bed Sheets 4-Piece Cooling Set',
    price: 59.99,
    originalPrice: 119.99,
    rating: 4.6,
    reviewsCount: 843,
    category: 'home',
    image: '/images/satin_sheets_set.png',
    description: 'Ultra-soft wrinkle-free cooling satin sheets with deep pockets for supreme luxury bed comfort.',
    longDescription: 'Indulge in night-time bliss with our premium Silky Satin Bed Sheets Set. Made from ultra-fine 100% polyester satin weave, these sheets offer an incredibly tactile, cooling, and friction-reducing experience that protects curly hair and keeps facial skin smooth and moisturized. The set comes with deep pocket sheets fitted with all-around heavy-duty elastic to hug mattresses up to 16 inches deep without slipping.',
    features: [
      'Includes 1 Flat Sheet, 1 Fitted Sheet, and 2 Pillowcases',
      'Friction-free satin material protects facial skin and curly hair',
      'Cool-to-the-touch breathable weave properties',
      'Deep pocket design fits up to 16” deep mattresses securely',
      'Wrinkle-resistant & machine-washable durability'
    ],
    stock: 45,
    colors: ['Midnight Blue', 'Pearl White', 'Champagne Gold', 'Cosmic Grey'],
    badge: 'Popular',
    isPopular: true
  },
  {
    id: 'ergonomic-office-chair',
    name: 'Ergonomic Wood-Accent High-Back Mesh Office Chair',
    price: 110.00,
    originalPrice: 189.99,
    rating: 4.7,
    reviewsCount: 219,
    category: 'home',
    image: '/images/ergonomic_office_chair.png',
    description: 'Premium adjustable high-back executive mesh desk chair featuring stunning natural wood-shell backing and advanced lumbar support.',
    longDescription: 'Elevate your office aesthetic and personal comfort with our high-back mesh office chair. This design blends executive functionality and mid-century luxury, incorporating a striking wooden veneer back shell casing with highly breathable woven mesh backing. Configured with a 3D adjustable headrest, multi-way adjusting armrests, customizable seat height, and synchronous tilt reclining, it guarantees complete back support for extended seating sections.',
    features: [
      'Stunning Walnut Wood-Veneer Back Panel Design',
      'Ultra-Breathable Premium Woven Mesh keeps you cool',
      '3D Adjustable Headrest & Ergonomic Spine Lumbar Arch Support',
      'Adaptive padded wood-trim folding 90° armrests',
      'Heavy Duty Nylon Swivel Wheel Casters with SGS pneumatic cylinder'
    ],
    stock: 8,
    badge: 'Premium Find'
  },
  {
    id: 'bounce-house-slide',
    name: 'Inflatable Commercial-Grade Bounce House & Water Slide',
    price: 120.00,
    originalPrice: 249.99,
    rating: 4.9,
    reviewsCount: 108,
    category: 'home',
    image: '/images/bounce_house_slide.png',
    description: 'Large heavy-duty outdoor kids bouncing castle obstacle course play center with high-power electric blower included.',
    longDescription: 'Bring the amusement park directly to your backyard with our Premium Inflatable Bounce House & Water Slide. Featuring structural reinforcements, double-stitched 420D Oxford Nylon material, climbing walls, deep dual slides, water spraying nozzles, and a spacious bouncing floor guarded by security mesh. Installs in under 2 minutes using the included 450W heavy-duty active air blower.',
    features: [
      'Heavy-Duty puncture resistant 420D Oxford Nylon material',
      'Includes 450W electric blower fan, ground stakes, and repair kit',
      'Large triple-activity zone with slide, wall climb, and bounce pool',
      'Safe high netting walls and padded bumper obstacles',
      'Convenient travel carrying bag included'
    ],
    stock: 6,
    badge: 'Adventure Toy'
  },
  {
    id: 'wavytalk-hair-curler',
    name: 'Wavytalk Automatic Rotating Tourmaline Curling Iron',
    price: 80.00,
    originalPrice: 139.99,
    rating: 4.7,
    reviewsCount: 911,
    category: 'beauty',
    image: '/images/wavytalk-hair-curler.jpg',
    description: '1-inch automatic rotating ceramic styling curler wand with negative ion care and digital LCD screen.',
    longDescription: 'Achieve perfect, salon-worthy bouncy waves in minutes with the Wavytalk Automatic Curler. Simply place a section of hair into the styling chamber, and with the press of a single button, the smart auto-rotating tourmaline barrel gently curls your hair safely and evenly. Built-in negative ion generators infuse hydration to cut down frizz, leaving your locks with a radiant, glossy, damage-free finish.',
    features: [
      'Automatic bidirectional rotation buttons for effortless styling',
      'Premium Tourmaline Ceramic barrel prevents excessive heat spots',
      'Digital LCD temperature scale from 280°F to 430°F',
      'High-concentration negative ion technology for shiny anti-frizz locks',
      '60-minute automated safety shut-off mechanism'
    ],
    stock: 31,
    colors: ['Blush Pink', 'Rose Gold', 'Matte Black'],
    badge: 'Trending Now',
    isPopular: true
  },
  {
    id: 'revlon-volume-brush',
    name: 'Revlon One-Step Hair Dryer Brush & Volumizer',
    price: 85.00,
    originalPrice: 124.99,
    rating: 4.7,
    reviewsCount: 3410,
    category: 'beauty',
    image: '/images/revlon-one-step.jpg',
    description: 'Oval blow dryer and style hot air brush configured with ionic technology, dynamic pin-bristles, and multiple heating levels.',
    longDescription: 'Dry, detangle, style, and volumize your hair in one single step sweep. The Revlon One-Step Blow Dryer generates perfect professional blowouts in half the typical time with minimal heat damage. Constructed with a custom oval styling body to lift hair roots easily, nylon-pin bristles to unravel knots, air venting grids to heat hair gently, and tourmaline ionic glazes to coat hair with smooth shine.',
    features: [
      'Unique Oval airflow cylinder shapes elegant curves and ultimate root volume',
      'Built-in Ceramic Coating and Advanced Tourmaline Ionic frizz control',
      'Tangle-free combination Nylon Pin and Tufted Bristles massage scale',
      '3 Tailored Heat/Speed Settings with true Cool Shot option',
      'Sleek lightweight ergonomic wand body configuration'
    ],
    stock: 28,
    badge: 'Glam Choice'
  },
  {
    id: 'beauty-skin-glow',
    name: 'Derma-S Advanced Skincare 4-in-1 Wand Device',
    price: 100.00,
    originalPrice: 149.99,
    rating: 4.6,
    reviewsCount: 198,
    category: 'beauty',
    image: '/images/beauty_skin_glow.png',
    description: 'Multi-mode pink facial skin wellness device featuring microcurrent therapy, red light, and thermo care.',
    longDescription: 'Reclaim radiant, youthful skin with the pink Derma-S skincare wand. This handheld 4-in-1 medical-grade aesthetic tool combines microcurrent stimulation (MC) to lift sagging muscles, micro-vibrations to boost serum absorption, therapeutic red light spectrums to reverse hyperpigmentation, and calming high-frequency warm thermal therapies to soothe redness.',
    features: [
      'Multi-spectral LED therapy for optimal skin cell regeneration',
      'Microcurrent toning increases skin tightness and elasticity',
      'Gentle warming head promotes blood circulation',
      'Intelligent touch sensors turn device on automatically upon skin contact',
      'USB-rechargeable sleek pink travel-friendly structure'
    ],
    stock: 18,
    badge: 'Aesthetic Select',
    isPopular: true
  },
  {
    id: 'handheld-steam-cleaner',
    name: 'Pressurized Handheld Multi-Purpose Steam Cleaner',
    price: 99.99,
    originalPrice: 134.99,
    rating: 4.8,
    reviewsCount: 228,
    category: 'home',
    image: '/images/handheld-steam.jpg',
    description: 'Hot pressurized steam chemical-free sanitizer washer with 9 piece accessory kit for kitchen, grout, upholstery, auto, and floor clean.',
    longDescription: 'Obliterate grease, dirt, grime, and mold safely and naturally. The Handheld High-Pressure Steam Cleaner blasts dynamic, high-temperature sanitizing water steam reaching up to 220°F without utilizing harsh commercial acids or bleaching solutions. Ready to steam in under 3 minutes, it comes equipped with a comprehensive multi-nozzle accessory package to refresh couches, clean bathroom grout, scrub stovetops, steam car seats, or press garments.',
    features: [
      '2500 Watts of steaming power shoots hot spray deeply',
      'Generates high heat pressurized steam continuously',
      '100% Eco-Friendly chemical free cleaning protection',
      'Includes bent spray nozzle, brush tool, window squeegee, and safety cap',
      'Extra-long power cord for easy household mobility',
      '6 Adjustable Steam Levels & Dual Switch, 221°F, 4.5 BAR , 15s Heat-Up,For Tile, Grout, Grease, Dirt, Sofa, Windows'
    ],
    stock: 22,
    badge: 'Sanitary Master'
  },
  {
    id: 'smokeless-indoor-grill',
    name: 'Modern Indoor Smokeless Electric BBQ Grill',
    price: 120.00,
    originalPrice: 159.99,
    rating: 4.8,
    reviewsCount: 412,
    category: 'kitchen',
    image: '/images/smokeless_indoor_grill.jpg',
    description: 'Indoor nonstick BBQ grill featuring automated steam smoke-filtering extractor fan, digital temperature dial, and tempered glass grill lid.',
    longDescription: 'Relish outdoor chargrilled barbecue steaks, burgers, behavior skewers, and salmon fillets any season of the year. Our premium Indoor Smokeless Electric Grill incorporates a high-power active air extractor fan loop to suck up soot, grilling smoke, and grease particles into charcoal water filter baths below, resulting in clean kitchen air. Plate is coated with ultra-slick heavy industrial ceramic nonstick surfaces.',
    features: [
      'Integrated active smokeless exhaust fan technology',
      'Rapid heating dual heating plates reaching up to 450°F',
      'Removable dishwasher-safe heavy nonstick griddle grill plates',
      'Large tempered glass viewport lid prevents splattering messy spots',
      'Automatic safety thermal controller prevents over-heating'
    ],
    stock: 14,
    badge: 'Chef Select'
  },
  {
    id: 'handheld-steam-vacuum',
    name: 'Handheld Steam Vacuum Cleaner',
    price: 99.99,
    originalPrice: 129.99,
    rating: 4.5,
    reviewsCount: 234,
    category: 'home',
    image: '/images/handheld-steam.jpg',
    description: 'Compact handheld steam vacuum for quick cleanups and spot treatments.',
    longDescription: 'Tackle tough stains and odors with the versatile handheld steam vacuum. Its powerful steam technology penetrates deep into fabrics and surfaces, while the compact design makes it easy to maneuver in tight spaces.',
    features: [
      '2500 Watts of steaming power shoots hot spray deeply',
      'Extra-long power cord for easy household mobility',
      '6 Adjustable Steam Levels & Dual Switch, 221°F, 4.5 BAR , 15s Heat-Up,For Tile, Grout, Grease, Dirt, Sofa, Windows'
    ],
    stock: 22,
    badge: 'Sanitary Master'
  },
  {
    id: 'step-on-trash-can',
    name: 'Rubbermaid Premier Series III Step-On Trash Can',
    price: 85.00,
    originalPrice: 139.99,
    rating: 4.6,
    reviewsCount: 162,
    category: 'home',
    image: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=600&auto=format',
    description: '13-Gallon charcoal black step-on trash bin featuring solid stainless steel metal rim accents, charcoal odor filters, and slow-close air hinge lids.',
    longDescription: 'Revamp household refuse disposal with the Rubbermaid Premier trash bin. Crafted with heavy-duty structural resin with high resistance to dents, finger scuffs, and household scratches, framed by an elegant stainless steel rim. Operates via robust extra-wide metal foot step levers and slow hydraulic air hinges that shut down lids softly and silently, and contains carbon filter chambers to trap odors.',
    features: [
      'Soft-close gas air cylinder eliminates lid slamming noise',
      'Premium Stainless Steel Rim holds trash liner bags in place securely',
      'Odor-Lock active charcoal filtration casing keeps air fresh',
      'Scuff-resistant carbon textured matte black finish panels',
      'Extra durable metal foot lever system tested over 100,000 presses'
    ],
    stock: 17,
    badge: 'Utility Gold'
  },
  {
    id: 'aster-cook-knives',
    name: 'Aster-cook 15-Piece Stainless Kitchen Knife Set',
    price: 80.99,
    originalPrice: 159.99,
    rating: 4.9,
    reviewsCount: 512,
    category: 'kitchen',
    image: '/images/knife-block.jpg',
    description: 'Premium carbon German stainless steel all-black knives set nested in striking black hardwood storage block with built-in sharpener.',
    longDescription: 'Prepare ingredients with master precision. The Aster-cook professional cutlery set includes a complete assortment of high-carbon rust-free German stainless steel chef, slicing, utility, paring, steak, and bread knives, plus sharpening steel rods and premium kitchen shears. Coated with specialized sleek FDA-grade black matte non-stick anti-slip materials.',
    features: [
      'High-Carbon German Stainless Steel offers razor sharp edges',
      'Gorgeous minimal black wooden block organizer with safety feet',
      'Ergonomic bolster handles provide perfect balance and leverage',
      'Food-safe black anti-wear nonstick coating prevents sticking',
      'Integrated sharpening slots for easy maintenance of blades'
    ],
    stock: 9,
    badge: 'Pro Chef'
  },
  {
    id: 'Commercial Electric Griddle',
    name: 'Electric Countertop Flat Top Griddle,110V 1600W Electric Flat Top Grill,Non-Stick',
    price: 99.99,
    originalPrice: 129.99,
    rating: 4.8,
    reviewsCount: 604,
    category: 'kitchen',
    image: '/images/electric-griddle.jpg',
    description: '20 inch by 10 inch flat-top heavy electric table griddle with precise heat adjust dials, grease channel traps, and cool-touch edges.',
    longDescription: 'Whip up huge family breakfasts of pancakes, golden eggs, strips of bacon, and hashed hashbrowns together on Chefman’s extra-large electrical griddle plate. Engineered with advanced heating elements to maintain consistent temperatures across the entire flat-top surface, and featuring a built-in slight angle tilt slope to drain cooking oils into dishwasher safe underneath slide containers.',
    features: [
      'Massive 200 sq. inch heavy flat nonstick griddle sheet',
      'Removable temperature control dial adjusts precisely from Warm up to 400°F',
      'Drainage channel slope feeds excess grease to removable drip tray',
      'Fully immersible flat plate in water once controller is detached',
      'Double-walled side stay-cool handles prevent finger burns'
    ],
    stock: 11,
    badge: 'Breakfast Star'
  },
  {
    id: 'carote-cookware-set',
    name: 'Carote Nonstick Granite Pots & Pans 10-Piece Set',
    price: 120.99,
    originalPrice: 149.99,
    rating: 4.8,
    reviewsCount: 954,
    category: 'kitchen',
    image: '/images/pan-set.jpg',
    description: 'Aesthetic eco-friendly granite stone ceramic cookware set featuring gorgeous wood-textured touch handles.',
    longDescription: 'Form, function, and style align in this beautiful Swedish design eco-friendly cookware collection from CAROTE. Forged with thick conducting aluminum alloy cores and glazed with a five-layer ultra-slick nonstick health granite granite stone glaze that is 100% PFOA, lead, and cadmium free. Textured cool-touch woodgrain-pattern handles offer comfortable grips and beautiful styling.',
    features: [
      'Eco-friendly PFOA-free Granite Nonstick Coating',
      'Includes frying pans, saucepans, casseroles with tempered lids, utensils',
      'High-magnetic inductive base heats quickly and fits gas, induction, electric',
      'Ergonomic heat-resistant wood-style Bakelite stay-cool handles',
      'Super-flat easy wipe interior minimizes water wash waste'
    ],
    stock: 11,
    badge: 'Aesthetic Kitchen',
    isPopular: true
  },
  {
    id: 'graco-car-seat',
    name: 'Graco SlimFit 3-in-1 Convertible Baby Car Seat',
    price: 125.99,
    originalPrice: 219.99,
    rating: 4.9,
    reviewsCount: 1422,
    category: 'home',
    image: '/images/car-seat.jpg',
    description: 'Ultra slim convertible child safety seat holding rear-facing toddlers to forward-facing kids up to 100 lbs.',
    longDescription: 'Keep your child safe, cozy, and perfectly nested inside the Graco SlimFit 3-in-1 Convertible seat. Featuring a smart space-saving narrow casing frame that frees up back seat space, this seat transitions seamlessly from rear-facing harness, to forward-facing harness, and to highback booster seats. Includes premium impact materials, dual cup holders, and high adjust straps.',
    features: [
      'Saves rear seat space with its unique 3-position compact design',
      'Grows seamlessly with your child from 5 lbs up to 100 lbs capacity',
      'Incredibly strong steel-reinforced internal frame for supreme collision defense',
      'Simply Safe Adjust Harness System coordinates headrest and straps together',
      'Breathable push-button washable plush seat pads'
    ],
    stock: 10,
    badge: 'Nursery Standard'
  },
  {
    id: 'dash-cam',
    name: 'Ultra-HD Dual Dashboard Car Dash Camera',
    price: 110.99,
    originalPrice: 149.99,
    rating: 4.7,
    reviewsCount: 328,
    category: 'electronics',
    image: '/images/dash-camera.jpg',
    description: 'Crisp wide-angle dual recording dash camera featuring integrated GPS tracking, night vision, and 64GB storage.',
    longDescription: 'Capture your travels in absolute clarity with this dual-lens dashboard camera. Incorporating professional-grade Sony sensors, it records ultra HD video for both the front road perspective and the inner car cabin simultaneously. Automatically records collisions via built-in G-sensors, loop-records over old logs seamlessly, and works flawlessly under extreme temperatures.',
    features: [
      'Dual-Channel True 1080p Front & Cabin recording',
      'Excellent night vision with F1.8 large aperture lens',
      'Seamless loop recording on included 64GB high-speed MicroSD card',
      'Instant G-sensor impact auto-locking file lock security',
      'Easy suction windshield mounting with adhesive option'
    ],
    stock: 15,
    badge: 'Tech Select'
  },
  {
    id: 'bullet-blender',
    name: 'NutriBullet Food Personal Bullet Blender Kit',
    price: 75.99,
    originalPrice: 129.99,
    rating: 4.8,
    reviewsCount: 789,
    category: 'kitchen',
    image: '/images/personal-blender.jpg',
    description: 'Compact personal bullet kitchen blender with cyclonic extraction system for high quality smoothies.',
    longDescription: 'The NutriBullet is the fastest, easiest solution for making nutrient-packed smoothies. Load it up with your favorite whole foods like nuts, berries and spinach, then push, twist and blend your way to a healthier lifestyle. Powerful motors and cyclonic extraction blades break down tough seeds, stems, and skins to unlock the vital nutrition inside.',
    features: [
      'Powerful cyclonic torque motor breaks down tough items instantly',
      'Unique extractor stainless-steel blades need no sharpening',
      'Includes 2 tall-to-go blending cups and spill-resistant travel lids',
      'Dishwasher safe components for minimal wash effort',
      'Sturdy heavy-duty brushed metal base aesthetic'
    ],
    stock: 19,
    badge: 'Top Rated'
  },
  {
    id: 'ceiling-fan',
    name: 'Modern Ceiling Fan with Integrated Ring LED Light',
    price: 150.99,
    originalPrice: 210.99,
    rating: 4.7,
    reviewsCount: 214,
    category: 'home',
    image: '/images/ceiling-fan.jpg',
    description: 'Low-profile flush mount ring light ceiling fan featuring modern matte wire mesh framing and multi-speed wireless remote.',
    longDescription: 'Optimize both illumination and air ventilation in your bedrooms or workspaces. This modern ceiling fan integrates a dimmable LED ring light surrounding low-profile fan blades. Offers multi-speed motor rotation, bidirectional operations for seasonal warming/cooling, and silent whisper-quiet operation. Installs easily with standard flush mounts.',
    features: [
      'Multi-speed silent reversible DC motor for year-round comfort',
      'Fully dimmable LED ring light with customizable color temperatures',
      'Wireless remote control and smart smartphone app synchronization',
      'Beautiful modern matte bronze wire mesh frame decoration',
      'Low-profile flush mount perfect for standard and low ceilings'
    ],
    stock: 12,
    badge: 'New Arrival'
  },
  {
    id: 'stanley-tumbler',
    name: 'Stanley Classic Trigger-Action Insulated Travel Tumbler',
    price: 50.00,
    originalPrice: 115.00,
    rating: 4.9,
    reviewsCount: 3104,
    category: 'home',
    image: '/images/stanley_tumbler.png',
    description: 'Thermal vacuum-insulated stainless steel double-walled travel cup with easy trigger-action sealing cap.',
    longDescription: 'Engineered for adventurers and commuter life alike, the Stanley Travel Tumbler utilizes legendary double-wall vacuum insulation to keep your morning coffee piping hot or your ice water cold for hours. Designed with a convenient trigger-action seal that lets you open, sip, and close the lid with a single hand, and styled with high-performance hammertone finish.',
    features: [
      'Double-wall vacuum insulation keeps thermal temperature for up to 30 hours',
      'Heavy-duty 18/8 food-grade stainless steel is completely rust-free',
      'Leakproof trigger-action button cap prevents accidental car spills',
      'Designed to fit perfectly within standard car cup holder dimensions',
      'BPA-free cap is fully dishwasher safe disassemble properties'
    ],
    stock: 35,
    colors: ['Hammertone Grey', 'Polar White', 'Classic Green', 'Matte Black'],
    badge: 'Trending'
  },
  {
    id: 'ninja-blender',
    name: 'Ninja Blast Portable Personal Rechargeable Blender',
    price: 60.00,
    originalPrice: 119.99,
    rating: 4.8,
    reviewsCount: 452,
    category: 'kitchen',
    image: '/images/blender.jpg',
    description: 'High-performance USB-C rechargeable portable personal single-serve smoothie blender with leakproof lid.',
    longDescription: 'Take your nutritional smoothies, protein shakes, and frozen margaritas anywhere you go with the Ninja Blast. Powered by a USB-C rechargeable battery pack that blends up to 15 times on a single charge. Fitted with Ninja’s signature high-velocity stainless steel extraction blade to slice through ice, frozen fruits, vegetables, and powders smoothly.',
    features: [
      'Powerful cordless blending action with USB-C rechargeable cell',
      'Signature Ninja Blast ice-crushing stainless-steel blades',
      'Fitted with sip-friendly leakproof lid and easy carrying loop',
      'One-touch automatic smart blending cycles for flawless results',
      'Incredibly lightweight, compact, and ideal for fitness bags'
    ],
    stock: 26,
    badge: 'Fitness Pick'
  },
  {
    id: 'sauvage dior',
    name: 'Sauvage by Christian Dior Parfum Spray 2 oz',
    price: 99.99,
    originalPrice: 140.00,
    rating: 4.8,
    reviewsCount: 228,
    category: 'beauty',
    image: '/images/sauvage.jpg',
    description: 'Luxury highback cardamom and amber notes men\'s cologne in a stylish revolver-styled black bottle casing.',
    longDescription: 'Unleash your charismatic presence with Azzaro The Most Wanted, an intensely sophisticated fragrance for the modern gentleman. This premium woody oriental parfum blends fresh cardamom, melt-in-the-mouth sweet caramel, and deep warm amber wood trails. Packaged in a striking signature all-black cylindrical revolver-barrel bottle casing.',
    features: [
      'Highly concentrated long-lasting executive Parfum density',
      'Rich warm scent profile: Cardamom, Toffee, and Amberwood',
      'Exquisite and distinctive industrial collectible cylinder casing',
      'Perfect fragrance selection for evening wear and special occasions',
      'Sourced and blended with premium French oils'
    ],
    stock: 14,
    badge: 'Luxury Fragrance'
  },
  {
    id: 'kerastase-serum',
    name: 'Kérastase Genesis Fortifying Scalp Serum',
    price: 85.99,
    originalPrice: 125.00,
    rating: 4.7,
    reviewsCount: 310,
    category: 'beauty',
    image: '/images/oily.jpg',
    description: 'Professional daily scalp fortifying serum infused with ginger root extracts to strengthen damaged fibers and prevent hair-fall.',
    longDescription: 'Give your hair roots the ultimate nutritional support. Kérastase Genesis Fortifying Serum is a daily scalp wellness solution designed to strengthen hair fibers from the anchor point, reducing hair fall arising from brushing or heat stress. Formulated with Aminexil, Ginger Root extracts, and Edelweiss Native cells to soothe irritation and build a healthy scalp barrier.',
    features: [
      'Significantly reduces hair fall caused by daily brushing damage',
      'Formulated with Aminexil 1.5% to preserve collagen networks',
      'Ginger Root extracts safeguard roots from external daily stressors',
      'Lightweight gel-like serum leaves zero greasy residue on hair',
      'Delightful, premium botanical fragrance trail'
    ],
    stock: 18,
    badge: 'Salon Exclusive'
  },
  {
    id: 'smart-watch',
    name: 'Elegant Rose-Gold Women’s Smart Watch Tracker',
    price: 110.99,
    originalPrice: 159.99,
    rating: 4.6,
    reviewsCount: 195,
    category: 'electronics',
    image: '/images/smart-watch.jpg',
    description: 'Premium circular smartwatch with flower-theme faces, heart rate tracking, and high-visibility OLED display.',
    longDescription: 'A perfect blend of luxury jewelry styling and advanced watch analytics. This rose-gold smartwatch monitors your sleep cycles, tracks heart-rate curves, acts as a pedometer, logs sports sessions, and alerts you to text messages. It features a bright circular OLED touch face configured with a wide range of elegant botanical dial visual skins.',
    features: [
      'Gilded Rose-Gold stainless steel outer ring with pink premium strap',
      '24/7 Heart rate, sleep quality, and fitness activity sensor matrix',
      'Over 50 custom elegant watch face visual catalog styles',
      'Waterproof housing rating allows for worry-free swimming',
      'Extra long battery life offering up to 8 days on single recharge'
    ],
    stock: 22,
    badge: 'Fashion Tech'
  },
  {
    id: 'tattoo-pen',
    name: 'Dragonhawk Rotary Tattoo Pen Machine Kit',
    price: 150.00,
    originalPrice: 199.99,
    rating: 4.7,
    reviewsCount: 88,
    category: 'beauty',
    image: '/images/tatto-fold.jpg',
    description: 'Professional rotary tattoo pen gun matching custom needles, color ink pots, and digital power board tools.',
    longDescription: 'Unleash your creative tattoo designs with this elite Dragonhawk Rotary Tattoo Pen. Constructed with a seamless aerospace-grade aluminum casing driven by a custom Japanese motor for low noise, gentle vibration, and stable stitch operations. Includes an adjustable LCD power brick, steel foot pedals, dual cartridge configurations, and skin practice pads.',
    features: [
      'Engineered with premium Japanese motor for absolute quiet operations',
      'Crafted from high-grade aerospace aluminum with sleek pink finish',
      'Intuitive digital power supply console for precise voltage adjustment',
      'Includes 20 starter needle cartridges and practice equipment layers',
      'Comfortable anti-slip ergonomic pen handle reduces artist fatigue'
    ],
    stock: 12,
    badge: 'Artist Select'
  },
  {
    id: 'lash-kit',
    name: 'Veyes Beauty DIY Eyelash Extensions Pro Starter Kit',
    price: 70.99,
    originalPrice: 115.00,
    rating: 4.6,
    reviewsCount: 142,
    category: 'beauty',
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=600&auto=format',
    description: 'Salon quality DIY lash clusters kit complete with quick bond sealer glue, lash remover, and applicator tweezers.',
    longDescription: 'Get glamorous, voluminous eyelashes at home instead of spending hundreds at high-end studios. This premium eyelash kit contains multiple rows of soft faux mink cluster lashes ranging from 8mm to 16mm, a high-strength double-ended lash bond and sealing glue, an ergonomically curved applicator tweezer, and a gentle rose-infused eyelash gel remover.',
    features: [
      'Faux mink lash clusters in assorted lengths (8mm to 16mm)',
      'Innovative 2-in-1 Bond & Seal lash glue prevents clumps and is waterproof',
      'Precision stainless-steel fiber tweezers designed for perfect placement',
      'Gentle oil-free lash clusters remover keeps your natural lashes healthy',
      'Guarantees fluffy, professional results lasting up to 2 full weeks'
    ],
    stock: 40,
    badge: 'Glam Pick'
  },
  {
    id: 'massage-table',
    name: 'Zen Wooden Portable Folding Salon Massage Table',
    price: 220.00,
    originalPrice: 350.99,
    rating: 4.8,
    reviewsCount: 94,
    category: 'beauty',
    image: '/images/massage-table.jpg',
    description: 'Triple-fold professional salon massage table with solid beech wood structure and therapeutic memory foam padding.',
    longDescription: 'Provide extreme therapeutic comfort with the Zen Folding Massage Table. Built upon a solid structural frame of selected beech wood and high-tension steel cords that supports up to 500 lbs. Padded with 2.5 inches of high-density memory foam lined with water-resistant PVC leather. Fully collapsible and easily carried in its premium canvas luggage bag.',
    features: [
      'Solid Select Beech Wood legs and heavy-duty corner reinforcements',
      '2.5-inch thick high-density therapeutic memory foam padding',
      'Lined with premium water-proof and oil-resistant luxury PVC leather',
      'Adjustable headrest angle, armrest supports, and customizable height settings',
      'Collapsible build includes a travel canvas carrying case with pocket guides'
    ],
    stock: 7,
    badge: 'Spa Grade'
  },
  {
    id: 'vacuum-cleaner',
    name: 'Ultra-Lightweight Cordless Stick Vacuum Cleaner',
    price: 120.00,
    originalPrice: 169.99,
    rating: 4.7,
    reviewsCount: 382,
    category: 'home',
    image: '/images/vacuum_cleaner.png',
    description: 'Multi-surface high-suction lightweight cordless stick vacuum with dual filtration and LED path headlights.',
    longDescription: 'Experience true cordless cleaning freedom. This ultra-lightweight cordless stick vacuum cleaner packs a brushless high-RPM motor, generating amazing cyclonic air suction to absorb dander, pet hair, dirt, and crumb particles from both dense carpets and hardwood flooring. Transitions easily into a handheld vacuum equipped with a crevice detail nozzle.',
    features: [
      'Amazing multi-surface cyclonic suction driven by a brushless motor',
      'Equipped with 4 detachable heads including a crevice nozzle and brush tools',
      'Luminous LED path headlights on base sweep find hidden dust under sofas',
      'Premium triple HEPA air filtration discharges pristine clean air',
      'Long-lasting rechargeable battery cell offers up to 40 minutes of clean time'
    ],
    stock: 14,
    badge: 'Home Essential'
  },
  {
    id: 'mobile-holder',
    name: 'Osmo Mobile 8 Gimbal Stabilizer for Phone, 3-Axis Stabilization',
    price: 110.99,
    originalPrice: 199.99,
    rating: 4.8,
    reviewsCount: 210,
    category: 'electronics',
    image: '/images/mobile-holder.jpg',
    description: 'Professional 3-axis gimbal stabilizer for smartphones with active tracking and gesture control.',
    longDescription: 'Capture smooth, cinematic footage with the Osmo Mobile 8 Gimbal Stabilizer. This advanced device features a 3-axis stabilization system that eliminates shake and jitter, allowing you to record professional-quality videos with your smartphone. It also includes active tracking, gesture control, and a variety of shooting modes to enhance your filming experience.',
    features: [
      '3-axis stabilization for smooth video capture',
      'Active tracking technology for following subjects automatically',
      'Gesture control for hands-free operation',
      'Multiple shooting modes including panorama and time-lapse',
      'Lightweight and portable design for easy transport'
    ],
    stock: 25,
  },
  {
    id: 'zero-sugar',
    name: 'Zero Sugar Electrolytes | 30-Count ',
    price: 80.99,
    originalPrice: 100.99,
    rating: 4.9,
    reviewsCount: 150,
    category: 'beverages',
    image: '/images/Zero-Sugar-Electrolytes.jpg',
    description: 'LMNT Zero Sugar Electrolytes - Raw Unflavored Salt | Drink Mix | 30-Count.',
    longDescription: 'Stay energized without the sugar crash with our Zero Sugar Energy Drink. Packed with natural flavors and electrolytes, this beverage provides a boost of energy while keeping you hydrated. Perfect for workouts, long drives, or any time you need a pick-me-up.',
    features: [
      'Zero sugar formula for guilt-free energy',
      'Infused with electrolytes for hydration',
      'Natural flavors for a refreshing taste',
      'Convenient 12-pack for on-the-go energy',
      'No artificial colors or preservatives'
    ],
    stock: 50,
    badge: 'Healthy Choice'
  },
  {
    id: 'computer-desk',
    name: ' Height Adjustable Computer Desk',
    price: 120.99,
    originalPrice: 200,
    rating: 4.8,
    reviewsCount: 120,
    category: 'home',
    image: '/images/height-adjustale-computer-desk.jpg',
    description: 'Ergonomic height adjustable computer desk with spacious work surface and cable management system.',
    longDescription: 'Enhance your productivity and comfort with our Height Adjustable Computer Desk. Designed for both sitting and standing positions, this desk features a spacious work surface, sturdy frame, and an integrated cable management system to keep your workspace organized.',
    features: [
      'Height adjustable for sitting or standing use',
      'Spacious work surface for monitors, laptops, and accessories',
      'Sturdy steel frame for stability and durability',
      'Integrated cable management system to reduce clutter',
      'Easy assembly with included instructions and tools'
    ],
    stock: 20,
    badge: 'Office Essential'
  },
  {
    id: 'dog grooming',
    name: 'Dog Grooming Vacuum',
    price: 90.99,
    originalPrice: 150.99,
    rating: 4.7,
    reviewsCount: 85,
    category: 'pet',
    image: '/images/grooming-vacuum.jpg',
    description: 'Pet grooming vacuum with adjustable suction and multiple attachments for safe and effective grooming.',
    longDescription: 'Keep your furry friends looking their best with our Dog Grooming Vacuum. This versatile tool features adjustable suction power and comes with multiple attachments to safely groom your pets, removing loose hair and reducing shedding.',
    features: [
      '1.5L Dust Cup Dog deshedding Brush with 7 Tools for Shedding Pet Hair',
      '11kPa Strong Suction, 59dB Low Noise,Clipper & Nail Grinder Included',
      '7-in-1 Grooming Kit, Deshedding Brush, 1.5L Dust Cup',
      '7 in 1 Pro Pet Grooming Kit, Keep the House Tidy: oneisall pet grooming kit with vacuum make home grooming easy',
      'Compact and lightweight design for easy handling'
    ],
    stock: 15,
    badge: 'Pet Care'
  },
  {
    id: 'meta-quest-2',
    name: 'Meta Quest 2 — Advanced All-In-One Virtual Reality Headset — 128 GB',
    price: 199.99,
    originalPrice: 399.99,
    rating: 4.9,
    reviewsCount: 200,
    category: 'electronics',
    image: '/images/Meta-Quest.jpg',
    description: 'Advanced all-in-one virtual reality headset with immersive experience and intuitive controls.',
    longDescription: 'Step into the future of virtual reality with the Meta Quest 2. This advanced all-in-one headset delivers an immersive experience with stunning visuals, intuitive controls, and a wide range of compatible apps and games.',
    features: [
      'Experience total immersion with 3D positional audio, hand tracking and easy-to-use controllers working together to make virtual worlds feel real.',
      'Come together in incredible social spaces and multiplayer arenas as you take in live events with friends and family, find your new workout crew or join adventures with fellow players.',
      '2 Touch Controllers (L&R), Glass Spacer, 2 AA Batteries, Quick Start Guide, Power Adapter (US, UK, EU, AU), Safety & Warranty Guide, Charging cable, VR headset2 Touch Controllers (L&R), Glass Spacer, 2 AA Batteries, Quick Start Guide, Power Adapter (US, UK, EU, AU), Safety & Warranty Guide, Charging cable, VR headset',
      '128 GB storage for apps, games, and media',
      'Built-in audio system for spatial sound'
    ],
    stock: 10,
    badge: 'Tech Trend'
  },
  {
    id: 'wireless-gaming',
    name: 'Xbox Wireless Gaming Controller | Elite Series 2 | Black | Consoles, PCs, TVs, mobile, and more | Adjustable Thumbsticks | Trigger Locks',
    price: 99.99,
    originalPrice: 249.99,
    rating: 4.9,
    reviewsCount: 150,
    category: 'electronics',
    image: '/images/wireless-gaming.jpg',
    description: 'Premium wireless gaming controller with adjustable thumbsticks and trigger locks for enhanced gameplay.',
    longDescription: 'Elevate your gaming experience with the Xbox Wireless Gaming Controller Elite Series 2. Designed for precision and comfort, this controller features adjustable thumbsticks, trigger locks, and a customizable button layout to suit your playstyle.',
    features: [
      'INTERCHANGEABLE COMPONENTS — Swap thumbstick toppers, D-pads, and paddles to tailor your controller to your preferred gaming style. Includes 6 thumbsticks, 4 paddles, 2 D-pads, carrying case, and charging dock.',
      'BUILT FOR LONG SESSIONS — Stay in the game with up to 40 hours of rechargeable battery life, wrap-around rubberized grips, and refined components built for durability and comfort.',
      'PLAY ACROSS EVERY SCREEN — Use XBOX Wireless, Bluetooth, or the included USB-C cable to play across XBOX Series X|S, XBOX One, Windows PC, and cloud. Plug in any compatible headset with the 3.5mm audio jack.',
      'ADJUSTABLE-TENSION THUMBSTICKS — Fine-tune your aim with thumbsticks that let you adjust resistance for improved accuracy, consistency, and control in every match.',

    ],
    stock: 20,
    badge: 'Gaming Pro'
  },
  {
    id: '26-Inch Aluminum Frame Hardside Checked Luggage, Metallic Silver',
    name: '26-Inch Aluminum Frame Hardside Checked Luggage, Metallic Silver',
    price: 99.99,
    originalPrice: 299.99,
    rating: 4.8,
    reviewsCount: 150,
    category: 'travel',
    image: '/images/hand-carry.jpg',
    description: 'Durable hardside checked luggage with aluminum frame, TSA-approved lock, and smooth-rolling spinner wheels.',
    longDescription: 'Travel in style and security with our 26-inch Aluminum Frame Hardside Checked Luggage. Built with a robust aluminum frame and high-quality polycarbonate shell, this luggage is designed to withstand the rigors of travel while keeping your belongings safe. It features a TSA-approved lock for added security and smooth-rolling spinner wheels for effortless maneuverability.',
    features: [
      'Medium Checked Luggage (26.6x18.1x10.6" | 85L | 9.1 lbs | 12-15 Days): Perfect for weekslong vacations, cross-country trips, or small family travel, this 26-inch hardshell suitcase features a generous 85L capacity. Despite its ample size, it weighs only 9.1 lbs, allowing you to pack more without hitting airline weight limits. Built for longer journeys of 10-15 days, it provides superior protection for all your essentials while remaining remarkably easy to maneuver.',
      'ZIPPERLESS ALUMINUM FRAME & LIGHTWEIGHT PC SHELL: Ditch compromised zippers! This hardshell suitcase combines a pry-proof, aerospace-grade aluminum frame for ultimate anti-theft security, with a world-renowned Covestro PC body. With 4 reinforced corners, it absorbs extreme impacts while remaining ultra-lightweight. You get metal-like protection without the heavy burden of a full-aluminum suitcase.',
      '5-Year Quality Promise & 24/7 Support: Every suitcase is backed by a reliable 5-Year Quality Promise. If you have any questions, please contact us anytime. Our dedicated support team will respond within 12 hours to provide a prompt and satisfactory solution. Purchase with confidence—we have got your back!',

    ],
    stock: 30,
    badge: 'Travel Essential'
  },
  {
    id: 'Licensed Dodge Ride on Push Car for Toddlers 1-3 Years with Handle & Music',
    name: 'Licensed Dodge Ride on Push Car for Toddlers 1-3 Years with Handle & Music',
    price: 110.99,
    originalPrice: 249.99,
    rating: 4.9,
    reviewsCount: 200,
    category: 'toys',
    image: '/images/push-car.jpg',
    description: 'Licensed Dodge ride-on push car for toddlers aged 1-3 years, featuring a handle and music for interactive play.',
    longDescription: 'Give your little one the thrill of driving with the Licensed Dodge Ride-On Push Car. Designed for toddlers aged 1-3 years, this ride-on car features a sturdy handle for parents to assist with steering, as well as built-in music to enhance the fun. Its realistic design and safe construction make it perfect for indoor and outdoor play.',
    features: [
      '【Dodge License】This officially licensed Dodge push car recreates the bold design of the Dodge Charger SRT Hellcat. One of the best toy cars for toddlers, it built with quality materials for a fun driving experience and makes a perfect gift for birthdays or Christmas.',
      '【Adjustable Push Handle】Designed for parent pushing on this toddler push car with handle, featuring a button-controlled push bar with 3 height settings (22.2, 29.7, 36.2) to fit different statures, and folds down easily for storage.',
      '【Smooth & Stable】Oversized 6.7″ wheels on this push car for toddlers 1-3 grip both indoor floors and outdoor pavement, while the wide wheelbase resists tipping for a smooth and stable ride across different terrains.',
      '【Easy Assembly】 Assembling this kids push car is straightforward with the step-by-step manual and online video guide, taking about 20 minutes. Backed by 24h customer support.',
      'Easy to assemble and maintain'
    ],
    stock: 25,
    badge: 'Toddler Fun'
  },
  {
    id: 'Colorful Lighting Baby Balance Bike Toys for 1 Year Old Boy Girl Gifts, 10-36 Month Toddler Balance Bike, No Pedal 4 Silence Wheels & Soft Seat First Riding on Toys, 1st Birthday Gifts',
    name: 'Colorful Lighting Baby Balance Bike Toys for 1 Year Old Boy Girl Gifts, 10-36 Month Toddler Balance Bike, No Pedal 4 Silence Wheels & Soft Seat First Riding on Toys, 1st Birthday Gifts',
    price: 88.99,
    originalPrice: 120.99,
    rating: 4.8,
    reviewsCount: 150,
    category: 'toys',
    image: '/images/bike-toy.jpg',
    description: 'Colorful lighting baby balance bike for 1 year old boy girl gifts, 10-36 month toddler balance bike, no pedal 4 silence wheels & soft seat first riding on toys, 1st birthday gifts',
    longDescription: 'Make your little one the center of attention with this colorful lighting baby balance bike. Perfect for toddlers aged 10-36 months, this balance bike features a no-pedal design with silent wheels and a soft seat for a comfortable ride. Ideal for birthdays or Christmas gifts.',
    features: [
      '【Colorful Lighting】This baby balance bike features vibrant colors and built-in LED lights that add excitement to every ride.',
      '【No Pedal Design】The no-pedal design allows toddlers to focus on balancing and steering without the complexity of pedals.',
      '【Silent Wheels】Equipped with silent wheels that provide a smooth and quiet ride, perfect for indoor use.',
      '【Soft Seat】The ergonomic soft seat ensures comfort during rides, encouraging longer play sessions.',
      '【Perfect Gift】A great gift for birthdays or Christmas, this balance bike is sure to delight any young rider.'
    ],
    stock: 30,
    badge: 'Toddler Fun'
  },
  {
    id: 'Rattan Small Bathroom Cabinet Narrow Toilet Paper Organizer Walnut',
    name: '7.9 D x 7.9 W Bathroom Organizer and Storage Cabinet for Small Space, Slim Corner Unit with Adjustable Shelf',
    price: 69.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviewsCount: 80,
    category: 'bathroom',
    image: '/images/mini-bathroom.jpg',
    description: 'Rattan small bathroom cabinet narrow toilet paper organizer walnut, 7.9 D x 7.9 W bathroom organizer and storage cabinet for small space, slim corner unit with adjustable shelf',
    longDescription: 'This rattan small bathroom cabinet is a perfect solution for small spaces. With its narrow design and adjustable shelf, it provides convenient storage for your bathroom essentials.',
    features: [
      'Slim & Space‑Saving Design: Measuring 7.9 D × 7.9 W × 27.6 H, this compact cabinet delivers generous storage despite its small footprint. Its narrow profile fits seamlessly into tight spots, corners or beside toilets, making it ideal for small bathrooms. Transform unused gaps into practical storage to organize your daily essentials and keep your space clutter‑free',
      'Stylish and Functional Design: The beautiful rattan - woven panels not only add a touch of natural charm but also serve as a unique decorative element. This small bathroom storage cabinet features an enclosed top, providing a safe spot to place your phone or bathroom essentials',
      '【Adjustable Shelf】The adjustable shelf allows you to customize the storage space based on your needs.',
      '【Slim Corner Unit】Designed to fit seamlessly into corner spaces, maximizing your available area.',
      '【Perfect for Small Spaces】Ideal for small bathrooms or any space where storage is limited.'
    ],
    stock: 25,
    badge: 'Space Saver'
  },
  {
    id: 'Girls Roller Skates for Kids Ages 3-5 5-8 6-12 Adjustable Light Up Roller Skates for Toddlers Beginners Boys Unicorn Mermaid Rainbow Gift for Indoor Outdoor Sports',
    name: 'Girls Roller Skates for Kids Ages 3-5 5-8 6-12 Adjustable Light Up Roller Skates for Toddlers Beginners Boys Unicorn Mermaid Rainbow Gift for Indoor Outdoor Sports',
    price: 59.99,
    originalPrice: 110.99,
    rating: 4.7,
    reviewsCount: 120,
    category: 'toys',
    image: '/images/roller-shoes.jpg',
    description: 'Adjustable light-up roller skates for kids ages 3-12, perfect for indoor and outdoor sports.',
    longDescription: '【Exquisite Packaging and Professional Accessories】: Each pair of toddler roller skates comes with an exquisite packaging box, perfectly presented, making it the perfect gift for children on birthdays, Christmas, holidays, and special occasions. Included is a pair of breathable and comfortable professional kids roller skating socks to enhance the skating experience, ensuring the child stays comfortable during long skating sessions.',
    features: [
      '【Colorful Wheels & Dreamy Mermaid Unicorn Design】: These girls skates makes it easy to grasp the balance and greatly increases safety and stabilit feature glowing wheels that flash with vibrant colors while skating, increasing visibility at night and adding extra fun for kids. The roller skate shoe upper is decorated with 3D silicone mermaid and unicorn patterns, combined with rainbow colors, creating a stylish yet playful look that makes children stand out in the crowd.',
      '【Improve Safety】: The kids skates are equipped with adjustable safety buckles, secure Velcro straps, and durable laces to provide better stability and safety while skating. The front brake design helps children maintain balance with ease, enhancing safety during skating. The 82A PU glowing wheels offer good visibility at night, helping to improve skating safety. Equipped with ABEC-7 precision bearings, the skates provide optimized performance and durability, ensuring a smoother ride every time.',
      'Durable construction for indoor and outdoor use',
      'Comfortable padding for extended wear',
      'Easy to put on and take off with secure straps'
    ],
    stock: 20,
    badge: 'Fun & Active'
  },
  {
    id: 'Bont Skates - Multi Sport Skate Backpack Travel Bag - Inline Ice Quad Speed Skating',
    name: 'Bont Skates - Multi Sport Skate Backpack Travel Bag - Inline Ice Quad Speed Skating',
    price: 55.99,
    originalPrice: 99.99,
    rating: 4.8,
    reviewsCount: 95,
    category: 'sports',
    image: '/images/travel-bag.jpg',
    description: 'Multi-sport skate backpack travel bag suitable for inline, ice, quad, and speed skating.',
    longDescription: 'The Bont Skates Multi Sport Skate Backpack is designed for skaters of all disciplines. With ample storage space and ergonomic design, it allows you to carry your skates and gear comfortably and securely.',
    features: [
      'Bont Skate Backpack is the perfect bag for carrying your skate equipment',
      'Large 28L capacity with laptop and mesh pouches inside, splash-proof water-resistant material',
      'Dimensions: 48 x 35 x 18cm [28L] Weight: 990g',
      'Roller skate bag, Inline skate bag, ice skate bag, skate bag, roller skate bag for women, hockey skate bag, figure skate bag',
      'Stylish design suitable for all types of skaters'
    ],
    stock: 18,
    badge: 'Skater\'s Choice'
  },
  {
    id: 'Govee Floor Lamp 3 with Luminblend+ Technology, 1000K-10000K Standing Lamp | Work with Matter, 2100lm Modern Floor Lamps for Living Room, Bedroom, Office',
    name: 'Govee Floor Lamp 3 with Luminblend+ Technology, 1000K-10000K Standing Lamp',
    price: 89.99,
    originalPrice: 149.99,
    rating: 4.7,
    reviewsCount: 110,
    category: 'home',
    image: '/images/lamp.PNG',
    description: 'Modern floor lamp with Luminblend+ technology, adjustable color temperature, and smart home compatibility.',
    longDescription: 'Govee Floor Lamp 3 with Luminblend+ Technology, 1000K-10000K Standing LampWork with Matter, 2100lm Modern Floor Lamps for Living Room, Bedroom, Office, Corner Lamp with Dynamic Scenes, DaySync',
    features: [
      'True-to-Life Color & Texture: This LED floor lamp features Govee LuminBlend+ technology, a 16-bit IC chip, and advanced algorithms to deliver realistic tones and delicate pastel shades, creating an atmospheric, imaginative space that matching your mood.',
      'Temperature and Brightness: This standing floor lamp delivers tunable 1000K-10000K, 2100lm@6500K, and 30% wider wall-washing vs Govee Floor Lamp 2. Glare-free, ideal floor lamp for reading and working. *Note: 2100lm only at 6500K; perceived brightness varies with color temp & room size.',
      'Double-Sided Skyline & Spot-Free Glow: This dimmable floor lamp for living room adds depth with an elegant backlight contour. 288 dense LEDs and optimized diffusion deliver soft, spot-free ambient lighting. A stunning decorative piece in any situation.',
      '2100 lumens brightness for well-lit spaces',
      'Sleek modern design suitable for any room decor'
    ],
    stock: 15,
    badge: 'Smart Lighting'
  },
  {
    id: 'Solar Fence Lights Outdoor, 2700/4000/6000K 3 Mode, 8-12H, Black, 8 PackIP65 Waterproof, Fence Lights Solar Powered for Outside, Backyard, Railing, Step, Patio,Wall and Home Improvement',
    name: 'Solar Fence Lights Outdoor, 2700/4000/6000K 3 Mode, 8-12H, Black, 8 PackIP65 Waterproof, Fence Lights Solar Powered for Outside, Backyard, Railing, Step, Patio,Wall and Home Improvement',
    price: 55.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviewsCount: 85,
    category: 'home',
    image: '/images/solar.PNG',
    description: 'Outdoor solar fence lights with adjustable color temperature and IP65 waterproofing.',
    longDescription: 'These solar fence lights are perfect for illuminating your outdoor space. With three color temperature options and IP65 waterproofing, they provide reliable lighting for your backyard, patio, or driveway.',
    features: [
      '3 Lighting Modes Fence Solar Lights: Our solar lights for fence offer 3 lighting modes: warm white/ Neutral White/ Cool White mode. suitable for daily lighting, illuminating your fence or courtyard. If youre looking for an environmentally friendly and economical way to light up your yard, this solar-powered option is sure to impress you',
      '2 Types of Installation: Fence post solar lights are relatively easy to install since they dont require any electrical wiring. outdoor fence lights can be mounted with screws (included) on outdoor walls, fences, next to the porch, or can be directly affixed with 3m adhesive (included), which does not require a professional electrician to install and saves labor costs',
      'Waterproof & Auto ON/OFF: This outdoor wall lights is made of weather resistant ABS material with a waterproof grade of IP65. The outdoor patio lights can withstand various outdoor conditions such as rain, snow, and extreme temperatures. And the solar powered fence lights automatically charge under sunlight. When the rechargeable battery is fully charged, the outdoor solar fence lights can light for at least 10 hours',
      'Easy to install with no wiring required',
      'Durable construction for long-lasting use'
    ],
    stock: 25,
    badge: 'Eco-Friendly'
  },
  {
    id: '8x10 Area Rugs Living Room: Fluffy Bedroom Soft Shag Rug Black GreyUpgrade Non-Slip High Pile Carpet Fuzzy Plush Indoor Floor Decor Shaggy Rugs for Kid Boys Girls Playroom Nursery Modern Home',
    name: '8x10 Area Rugs Living Room: Fluffy Bedroom Soft Shag Rug Black GreyUpgrade Non-Slip High Pile Carpet Fuzzy Plush Indoor Floor Decor Shaggy Rugs for Kid Boys Girls Playroom Nursery Modern Home',
    price: 55.99,
    originalPrice: 99.99,
    rating: 4.6,
    reviewsCount: 95,
    category: 'home',
    image: '/images/carpet.PNG',
    description: 'Ultra Soft Fluffy 8x10 Area Rugs for Living Room: shag rug treat your feet to cloud-like comfort with our ultra-soft, high-density plush microfiber pile—designed to stay fluffier longer without shedding. Whether walking, sitting, or lying down, each step feels luxuriously soft. Furry fibers resist matting, keeping the plush texture season after season. Ideal for bedroom, living room, or nursery',
    longDescription: 'Upgraded Non-Slip Backing: 8×10 fluffy area rug is highly soft with a high-density sponge interlayer, and the non-slip bottom with small. Built with a thick felt base and dense latex dots, this living room rug offers strong traction to enhance grip and help prevent slipping on vinyl, hardwood, or tile floors. Designed for pet-friendly homes, and child-safe spaces, this skid-resistant design minimizes movement, providing added safety and comfort',
    features: [
      'Modern Design: This soft fluffy area rugs for Living Room Bedroom is designed with a modern minimalist aesthetic that elevates both comfort and visual appeal. Whether placed in the living room, bedroom, playroom, or nursery, its clean and understated look blends effortlessly into any space, creating a cozy, welcoming vibe. Available in various colors and sizes to suit your unique decor needs',
      'Functional Advantage: Combining comfort and practicality, 8×10 fuzzy fluffy area rugs delivers thermal insulation and sound dampening, fostering a warm and peaceful environment. Its gentle surface cushions every step while helping prevent scratches on your floors. With its non-slip bottom, it ensures safe use—making it an excellent choice for families with young children or elderly individuals',
      'Complete Package: Your order contains one 8x10 rug (Dimensions: 120"L x 96" W x 1.8"D). For any questions about your rug, our customer service team is ready to assist with any inquiries',
      'Please Note: The actual living room Rug color may show slight differences from product images due to lighting conditions and screen display variation.This 8x10 shag fuzzy bedroom rug arrives vacuum-packed. Simply lay it flat for 2–3 days, and it will return to its full, fluffy form',
      'Stylish design that complements modern home decor'
    ],
    stock: 20,
    badge: 'Home Comfort'
  },
  {
    id: 'HAPPRUN 2500 ANSI Lumens Outdoor Projector with Built-in Streaming Apps, 4K Decoding Resolution, Dolby Audio, WiFi 6 and Bluetooth 5.2 for Indoor and Outdoor Home Theater',
    name: 'HAPPRUN 2500 ANSI Lumens Outdoor Projector with Built-in Streaming Apps, 4K Decoding Resolution, Dolby Audio, WiFi 6 and Bluetooth 5.2 for Indoor and Outdoor Home Theater',
    price: 125.99,
    originalPrice: 259.99,
    rating: 4.7,
    reviewsCount: 130,
    category: 'electronics',
    image: '/images/projecter.PNG',
    description: '[ Built-in Streaming System ] – No extra equipment needed. This smart projector gives you direct access to over 1,000 apps, including Netflix, Prime Video, YouTube, and Hulu. With plug-and-play convenience, it makes movie watching effortless and hassle-free',
    longDescription: '[ 2,500 ANSI Lumens Brightness ] – Unlike standard tv projectors (500–1,000 lumens) that require a pitch-dark room, our high-brightness outdoor projector delivers vibrant, razor-sharp images even with lights on or in daylight. Perfect for home theaters, living rooms, and outdoor movie nights under the',
    features: [
      '[ No Manual Adjustments Needed ] – Smart AI instantly analyzes your room and automatically adjusts focus and image alignment. No matter where you place it—on a table, nightstand, wall, or ceiling—the auto focus projector optimizes instantly for a perfect picture. No more fiddling with settings!',
      '[ 4K Decoding Resolution ] – The HAPPRUN KC7 PRO projector delivers stunning 4K decoding resolution with a 20,000:1 contrast ratio and 95% color gamut for razor-sharp, lifelike images. With HDR10+ support, it reveals richer colors, deeper blacks, and enhanced shadow detail—bringing the cinema experience straight to your living room',
      '[ Immersive Theater-Quality Sound ] – Dual 10W high-fidelity speakers with Dolby Audio produce rich, balanced sound featuring crisp highs and deep bass. Every detail shines with stunning clarity, bringing true cinematic audio to your living room with this home theater projector'
    ],
    stock: 15,
    badge: 'Home Theater'
  },
 {
    id: 'Contixo F23 GPS Drone With Camera, 46 Min Flight Time, 4.5" Screen Remote, Follow Me, Waypoints, 5GHz FPV Transmission, Return to Home, Hand Gestures, Orbit Mode Foldable Drones For Teens & Adults',
    name: 'Contixo F23 GPS Drone With Camera, 46 Min Flight Time, 4.5" Screen Remote, Follow Me, Waypoints, 5GHz FPV Transmission, Return to Home, Hand Gestures, Orbit Mode Foldable Drones For Teens & Adults',
    price: 80.99,
    originalPrice: 150.99,
    rating: 4.9,
    reviewsCount: 89,
    category: 'electronics',
    image: '/images/dron.PNG',
    description: 'ADVANCED GPS & SMART FLIGHT MODES – The Contixo F23 Drone Navigates with precision using built-in GPS features including Follow Me, Waypoint Flight, Orbit Mode, and Return to Home, hands-free control at any skill level, giving you total control and safety during every flight.',
    longDescription: 'LONG FLIGHT TIME WITH DUAL BATTERIES – Enjoy up to 46 minutes of total flight time with two included 7.4V 1600mAh batteries of this compact travel drone , each delivering up to 23 minutes per charge for extended outdoor adventures and a 600-ft video transmission range via 5GHz WiFi.',
    features: [
      'SMART CONTROLLER WITH 4.5" SCREEN – The camera drone monitor your live camera feed, flight path, and telemetry on a built-in 4.5" screen controller—no smartphone needed for real-time video and control.',
      'HD 720P CAMERA WITH ADJUSTABLE LENS – The GPS drone captures crystal-clear aerial footage with a 1280×720 resolution camera, featuring a 60° field of view and an adjustable angle from -90° to 0° for the perfect shot every time.',
      'NO FAA REGISTRATION REQUIRED – The palm-sized drone is weighing just 8.3 oz, under the FAA registration threshold, offering a hassle-free flying experience right out of the box.'
    ],
    stock: 20,
    badge: 'Drones'  
  },
  {
    id: 'L\'AGRATY Faux Rabbit Fur Throw Blanket for Couch, 50\'\' x 60\'\', Cocoa Brown Soft Cozy Bubble Fluffy Blanket for Sofa Bed, Thick Warm Plush Fuzzy Throw for Room Home Decor, Luxury Gift for Women Mom',
    name: 'L\'AGRATY Faux Rabbit Fur Throw Blanket for Couch, 50\'\' x 60\'\', Cocoa Brown Soft Cozy Bubble Fluffy Blanket for Sofa Bed, Thick Warm Plush Fuzzy Throw for Room Home Decor, Luxury Gift for Women Mom',
    price: 55.99,
    originalPrice: 99.99,
    rating: 4.8,
    reviewsCount: 75,
    category: 'home',
    image: '/images/wool.PNG',
    description: 'Soft and cozy faux rabbit fur throw blanket for couch, sofa, or bed, perfect for home decor and gifting.',
    longDescription: 'Wrap yourself in luxury with the L\'AGRATY Faux Rabbit Fur Throw Blanket. Measuring 50" x 60", this plush and fluffy blanket is perfect for adding warmth and style to your living room or bedroom. Its soft texture makes it ideal for snuggling on chilly evenings.',
    features: [
      'Ultra Soft & Furry: Our Rabbit Fur Thick Blanket is soft to the touch and perfect for snuggling up on the couch or bed in cold weather, making you feel like you\'re on a cloud. The bubble faux rabbit fur blanket is made of 650GSM premium microfiber polyester, which is extra soft, fuzzy, and fluffy, making it the perfect companion to keep you warm during the fall and winter months',
      'Reversible Design & Thickness: Our faux fur aesthetic blanket is made of 650GSM rabbit fur fabric and 200GSM fannel fleece fabric lining, this plush blanket is absolutely cozy and thick, and the fabric is fade-resistant, anti-pilling, and anti-static, providing long-lasting softness and durability. The premium and beautiful double sided fabric makes the bubble rabbit fur blanket reversible for extra warmth, an ideal balance of weight and heat for the winter months',
      'Soft and cozy texture perfect for snuggling',
      'Durable construction for long-lasting comfort',
      'Elegant design that complements any home decor'
    ],
    stock: 30,
    badge: 'Home Comfort' 
  },
  {
    id: 'Bamworld Plant Stand with Grow Light Plant Shelf for Mutiple Pots Large Plant Holder for Living Room Patio Boho Home Decor for Gardening Warm Light',
    name: 'Bamworld Plant Stand with Grow Light Plant Shelf for Mutiple Pots Large Plant Holder for Living Room Patio Boho Home Decor for Gardening Warm Light',
    price: 55.99,
    originalPrice: 99.99,
    rating: 4.8,
    reviewsCount: 75,
    category: 'home',
    image: '/images/garden.PNG',
    description: 'A stylish plant stand with a built-in grow light, perfect for adding greenery to your living space.',
    longDescription: 'Flower Stand with Grow Light: The plant light contains 3 supplemental light modes: 1. 48 leds warm white(3000k), only 3000k high uniform light ,like sunlight improve seeding growth ; 2. Warm (660nm): promote plant growth , flowering and fruit; 3. Full Warm White (380nm-780nm), Provide universal full spectrum which can meet the light conditions your plants need most in different stages',
    features: [
      '>10 Pots Large Plant Table: The wooden plant shelf includes 10 shelves, which can hold 11-25 pots of regular size. it can hold a high plant pot plant; Bearing up to 150 pounds, it is recommended to place a heavier flower pot below and a lighter flower pot on the upper layer.',
      'Hanging Flower Stand: Bamworld Plant Table\'s unique hanging functionality. With a spacious 30-inch center and 30”*11.8”*42.5 dimensions, this versatile shelf accommodates tall plants and offers the option to hang it, adding a dynamic dimension to your indoor or outdoor space Perfect as a gift for a plant lover.',
      'Carbonized Natural Wood: Eucalyptus wood is carbonized at 300°C to enhance waterproof performance and extend service life for both indoor and outdoor use, though outdoor durability may be slightly shorter.',
      'Easy to assemble and use'
    ],
    stock: 20,
    badge: 'Home Decor'
  },
  {
    id: 'Skechers Women\'s Go Walk Flex Grand Entry Hands Free Slip-Ins, Air-Cooled Memory Foam Insole, ULTRA GO Cushioning, Machine Washable, Vegan',
    name: 'Skechers Women\'s Go Walk Flex Grand EntryHands Free Slip-Ins, Air-Cooled Memory Foam Insole, ULTRA GO Cushioning, Machine Washable, Vegan',
    price: 79.99,
    originalPrice: 129.99,
    rating: 4.5,
    reviewsCount: 120,
    category: 'shoes',
    image: '/images/shoes.PNG',
    description: 'Comfortable and stylish walking shoes with advanced cushioning technology.',
    longDescription: 'EFFORTLESS SLIP-ON DESIGN: These slip on shoes for women feature a convenient hands-free entry with molded heel panel and stretch laces for easy on and off',
    features: [
      'SUPERIOR COMFORT TECHNOLOGY: Ultra Go cushioning and Air-Cooled Memory Foam insole provide exceptional comfort for all-day wear',
      'SECURE FIT: Heel Pillow technology and bungee closure system ensure these slip on sneakers for women stay securely in place',
      'VERSATILE PERFORMANCE: Super flexible traction outsole makes these womens slip on shoes perfect for walking and everyday activities',
      
    ],
    stock: 25,
    badge: 'Footwear'
  },
  {
    id: 'Rain Shower Head with Handheld Showerhead, Chrome 1.8GPM 460311 12" High Pressure Rainfall Shower Heads, 9 Sprays Handheld Showerheads, Magnetic Docking, Power Jets, 59" Shower Hose',
    name: 'Rain Shower Head with Handheld Showerhead, Chrome 1.8GPM 460311 12" High Pressure Rainfall Shower Heads, 9 Sprays Handheld Showerheads, Magnetic Docking, Power Jets, 59" Shower Hose',
    price: 55.99,
    originalPrice: 110.99,
    rating: 4.6,
    reviewsCount: 95,
    category: 'bathroom',
    image: '/images/shower.PNG',
    description: 'High-pressure rain shower head with handheld showerhead, multiple spray settings, and magnetic docking.',
    longDescription: 'Upgrade technology ensure amazing showering experience, compare with original magnetic shower head, our rain shower head adopts strong metal magnetic combin buckle structure which can hold your handheld shower head firmly (Patent NO:US011857983B2 & US12269049B1)',
    features: [
      'Rainforest experience in home, our high pressure shower heads has 278 spray nozzles committed to provide smooth rain feeling. You can enjoy a truly rain showering experience which leaves you a feeling of relaxing and comfortable',
      'Careful design brings customers a better experience, our shower heads has 274 anti-clog nozzles plus 4 big strong massage nozzles, you will never worry about cleaning nozzles. What\'s more, 4 big strong massage nozzles flow strong water to your head or shoulder which can massage your body well',
      'Magnetic Docking System: Easily switch between the rainfall and handheld showerheads with the convenient magnetic docking system.',
      'Durable Chrome Finish: The chrome finish not only adds a sleek look to your bathroom but also resists tarnishing and corrosion.',
      'Easy Installation: Comes with all necessary hardware for quick and easy installation.'
    ],
    stock: 30,
    badge: 'Bathroom Upgrade'
  },
  {
    id: 'MAXYOYO Folding Sofa Bed, Convertible Chair Bed with Pillow Foldable Couch with Back Support, Portable Fold Out Chair Comfy Floor Sofa for Living Room Bedroom, Dark Grey, Single',
    name: 'MAXYOYO Folding Sofa Bed, Convertible Chair Bed with Pillow Foldable Couch with Back Support, Portable Fold Out Chair Comfy Floor Sofa for Living Room Bedroom, Dark Grey, Single',
    price: 80.99,
    originalPrice: 150.99,
    rating: 4.7,
    reviewsCount: 110,
    category: 'home',
    image: '/images/fold.PNG',
    description: 'Convertible folding sofa bed with pillow, back support, and portable design for living room or bedroom.',
    longDescription: 'Headrest and Lumbar Pillow: The Headrest and Lumbar Pillow set is designed to provide superior comfort and support, offering a luxurious experience whether you\'re sitting or reclining. The headrest is designed with strap and buckle, ensuring a secure and stable attachment to the folding sofa, effectively preventing any unwanted shifting or displacement. The lumbar pillow supports the natural curve of your lower back, alleviating discomfort during extended periods of sitting',
    features: [
      'Durable Fabric: Crafted from premium corded fabric, this material offers a unique visual and tactile experience, elevating the ambiance of your living space. The size of the folding sofa bed is about 33.5"x74.8", which would be tailored to provide comfortable seating or bed for one person',
      'Comfortable Shredded Foam Filling: The cushion is filled with shredded foam, meticulously crafted to provide superior comfort and support. This innovative filling molds to your body contours, offering personalized cushioning that relieves pressure points and promotes relaxation',
      'Portable & Foldable: Lightweight and foldable design allows for easy storage and transport.',
      'Durable Construction: Made with high-quality materials to ensure long-lasting use.', 
      ],
    stock: 30,
    badge: 'Home Comfort'  
  },
  {
    id: 'Ring Pan-Tilt Indoor Cam (newest model) — See all around your home or business with 360° pan coverage, HD video, plus Two-Way Talk (2024 release), White',
    name: 'Ring Pan-Tilt Indoor Cam (newest model) — See all around your home or business with 360° pan coverage, HD video, plus Two-Way Talk (2024 release), White',
    price: 55.99,
    originalPrice: 110.99,
    rating: 4.8,
    reviewsCount: 100,
    category: 'electronics',
    image: '/images/camera.PNG',
    description: 'Ring Pan-Tilt Indoor Cam with 360° pan coverage, HD video, and two-way talk for home security.',
    longDescription: 'The Ring Pan-Tilt Indoor Cam is the newest model that allows you to see all around your home or business with 360° pan coverage. It features HD video quality and two-way talk, making it easy to communicate with anyone in the room.',
    features: [
      'See all around — Control your view with Pan-Tilt Indoor Cam, featuring a smooth 360° view you control from your phone.',
      'Find your perfect angle — Pan 360° around your home and tilt up and down, all in the Ring app.',
      'Know and respond in real time — View and respond to activity with Live View and Two-Way Talk.',
      'Easy Installation: Simple setup process with user-friendly instructions.',
      'See clearly, day or night — Get a clearer picture at any hour with HD Video and Color Night Vision.'
    ],
    stock: 20,
    badge: 'Home Security'
  },
  {
    id: 'Potane Precision Vacuum Machine,Pro Food Sealer with Built-in Cutter and Bag Storage(Up to 20 Feet Length), Both Auto Manual Options,2 Modes,Includes 2 Bag Rolls 11”x16’ and 8”x16’,Compact Design',
    name: 'Potane Precision Vacuum Machine,Pro Food Sealer with Built-in Cutter and Bag Storage(Up to 20 Feet Length), Both Auto Manual Options,2 Modes,Includes 2 Bag Rolls 11”x16’ and 8”x16’,Compact Design',
    price: 89.99,
    originalPrice: 140.99,
    rating: 4.7,
    reviewsCount: 90,
    category: 'kitchen',
    image: '/images/sealer.PNG',
    description: 'Professional food vacuum sealer with built-in cutter, bag storage, and multiple sealing modes.',
    longDescription: 'A WORKHORSE FOR HOUSEHOLD USE: The pre-programmed settings for each food mode are strictly tuned by engineers, allowing you to seal like a pro. It can be used over 100 times continuously, perfect for bulk foods, leftovers, and valuable items.',
    features: [
      'ONE-HAND & C-TYPE HALF-WRAPPED CHAMBER DESIGN: This machine is designed for one-handed operation. The lid can be easily locked and is user-friendly. The construction prevents the components and functions from becoming dusty, rusty, and damaged.',
      'Auto & Manual Options: Choose between automatic and manual sealing modes to suit your specific needs, whether you are sealing delicate items or larger quantities.',
      'ALL-INCLUSIVE VERSATILE MODEL: This all-inclusive machine was designed with built-in bag storage and a cutter bar, an accessory port for sealing containers, jars, bottle stoppers, 2 bag rolls (11”x16’ and 8”x16’), and an extra foam gasket for replacement.',
      'Durable Construction: Made with high-quality materials for long-lasting performance.',
      'HIGH-POWER VACUUM AND RELIABLE CONTINUOUS SEALING: The POTANE VS5736 uses an 8 mm sealing element (3 mm sealing width) and a brushless mechanical motor compared to the 3 mm sealing element (1-2mm sealing width) and toy motor of others.'
    ],
    stock: 25,
    badge: 'Kitchen Essential'
  },
  {
    id: 'Phueut Pressurized Handheld Multi-Surface Natural Steam Cleaner with 12 pcs Accessories, Multi-Purpose Steamer for Home Use, Steamer for Cleaning Floor, Upholstery, Grout and Car (Grey)',
    name: 'Phueut Pressurized Handheld Multi-Surface Natural Steam Cleaner with 12 pcs Accessories, Multi-Purpose Steamer for Home Use, Steamer for Cleaning Floor, Upholstery, Grout and Car (Grey)',
    price: 59.99,
    originalPrice: 130.99,
    rating: 4.6,
    reviewsCount: 85,
    category: 'home',
    image: '/images/floor.PNG',
    description: 'Handheld multi-surface steam cleaner with pressurized steam and 12 accessories for versatile cleaning.',
    longDescription: 'The Phueut Pressurized Handheld Multi-Surface Natural Steam Cleaner is designed for efficient and effective cleaning of various surfaces in your home. With its pressurized steam and included accessories, it can tackle floors, upholstery, grout, and even your car.',
    features: [
      'POWERFUL HOT STEAM - 1050 watts with 3-5 minutes fast heat-up and emits pressurized powerful hot steam 230℉ for up to 8-12 minutes',
      'MULTI-SURFACE CLEANING - Steamer is suited for virtually all hard surfaces including: ceramic, marble and sealed hard wood. It\'s great for tile, sinks, stoves, windows, sofa, toy and car',
      'CHEMICAL FREE & SAFE - Phueut steam cleaners for home use 100% Chemical free with no harmful fumes or residue. Safety child cap extra protects your families\' safety! Healthy and friendly steamer for kids and pets',
      '12-PIECE ACCESSORIES SET - This steam cleaner comes with exclusive free 12 pieces accessory kit, Includes 4 round brushes and other attachments to meet your different needs. Our all-in-one steamer can deep clean for your home',
      'LARGE WATER TANK - Steam cleaner features a large water tank of 350ml capacity (recommended load capacity is within 280ml) which allows you to focus on cleaning, instead of refilling often. The ergonomic handle reduces hand strain, allowing for comfortable use even during extended cleaning sessions'
    ],
    stock: 20,
    badge: 'Home Cleaning'
  }
];
